### ISSUE TITLE
Game crashes right when I open a song

### ISSUE THREAD

**Issue by NoobManWasTaken** [YoshiCrafter29/YoshiEngine#11]
I didn't even edit anything, it just crashes when I enter any song
[](https://cdn.discordapp.com/attachments/929042489015406592/932710154204483634/Screenshot_299.png)

**Comment by B01Coding** [comment]
Pls Fix

**Comment by YoshiCrafter29** [comment]
Yeah, it's a bug.

Enable everything in Options > GUI Options, it's patched in the newest version.
