### ISSUE TITLE
Bug Report: haxe.xml.XmlParserException

### ISSUE THREAD

**Issue by Megalonumber0ne** [YoshiCrafter29/YoshiEngine#115]
## Which target are you using?
- Windows

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
I tried to add the trees from week 6 into the engine, it didn't work so i converted the TXT into an XML, still didn't work so I completley remade the XML file and got the error. Here is the XML file
![image](https://user-images.githubusercontent.com/87905744/159174575-0036bf67-ed1d-4aa4-b49d-c2abbb8dfe67.png)

## Please describe your issue. Provide extensive detail and images if possible.
The game gives me an error whenever i add the trees from week 6 to the game, here is the error log incase something can be done with it:
![image](https://user-images.githubusercontent.com/87905744/159174620-f32acca3-5c1b-4c99-a1a9-cb3b03d50b1f.png)

**Comment by Megalonumber0ne** [comment]
Forgot to add this but when i press Ok this happens
![image](https://user-images.githubusercontent.com/87905744/159174649-72a9f614-eda0-475f-87ea-7223c1f5042a.png)
Pressing Ok again will proceed to crash the engine completley forcing me to reopen it

**Comment by YoshiCrafter29** [comment]
![image](https://user-images.githubusercontent.com/81191621/159179545-82ed4dbf-132a-4882-92be-7a70e7019b68.png)
You forgot the " to close the height value. Not an engine issue, closing.

**Comment by Megalonumber0ne** [comment]
Now that you're just mentioned that I realised how badly i missed that, thanks for helping
