### ISSUE TITLE
How do i change character mid-song without/with code?

### ISSUE THREAD

**Issue by RegentTax** [YoshiCrafter29/YoshiEngine#118]
I need to know how to change character mid song without/with code does anyone knows how to do that?
(Example of what im talking about : https://youtu.be/GqeJKvo6lZc?t=9)

**Comment by YoshiCrafter29** [comment]
Check [this](https://github.com/YoshiCrafter29/Yoshi-Engine-code-samples/blob/main/Haxe/Change%20Character%20mid-song.hx) and [this](https://github.com/YoshiCrafter29/Yoshi-Engine-code-samples/blob/main/Haxe/Change%20Boyfriend%20mid-song.hx)
