### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by itsDARK768** [YoshiCrafter29/YoshiEngine#119]
## Which target are you using?
Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.7.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Not yet really

## Please describe your issue. Provide extensive detail and images if possible.
The stage even though I typed in the correct code and such will simply not load, but everything else like the song loads, this applys to all hscript based scripts I think.
---

**Comment by blissedandpissed** [comment]
whats the code? do you have it loaded in your song_conf.hx/json file, along with your stage.hx file?

**Comment by itsDARK768** [comment]
yes i do with a hx/json and i wrote me stage in json and added the script to the song i wanted it on and it just does not work

**Comment by itsDARK768** [comment]
but i am on linux sooo

**Comment by YoshiCrafter29** [comment]
Have you checked the in-game logs?

**Comment by BernardoGP4504** [comment]
have you pressed [F6] or [Fn] + [F6] (in some computers) to check the logs in-game
