### ISSUE TITLE
100k crash game

### ISSUE THREAD

**Issue by alarmingly** [YoshiCrafter29/YoshiEngine#12]
![m i l f  when 100k](https://user-images.githubusercontent.com/83265784/150588422-2d82bf05-7999-4545-b5a1-4cf8e9e6f793.png)
just bruh
100 keys crah game
the game is SAD
i don't even know anymore

**Comment by YoshiCrafter29** [comment]
It's normal, cause the Strums animations haven't been set for 100 keys in the Default Note.hx
Copy it over to your mod and add a 100 keys scheme to it (the array of array of array of string at the very top)
