### ISSUE TITLE
Bug Report: [error when put a psych engine icon]

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [YoshiCrafter29/YoshiEngine#121]
## Which target are you using?
- [x] Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.7.0

## Please describe your issue. Provide extensive detail and images if possible.
---i was want create my chrataher, i put 300x130 icon and got this error message if "a 150 image has a 1 sprite or more"

**Comment by dimuzicle** [comment]
u need to put 300x1**5**0

**Comment by YoshiCrafter29** [comment]
you need to put 300x150
