### ISSUE TITLE
Bug Report: a funny bug

### ISSUE THREAD

**Issue by fnfbuttomanybugs** [YoshiCrafter29/YoshiEngine#122]
## Which target are you using?
 Windows

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.7.0

## Please describe your issue. Provide extensive detail and images if possible.
---dis is really funny 
![Screenshot 2022-03-25 160729](https://user-images.githubusercontent.com/83528547/160080476-d3386b4e-3bd1-4c1c-90b3-27e9b7d0b417.png)

**Comment by fnfbuttomanybugs** [comment]
an error bug if when i press 7

**Comment by McJonnycat** [comment]
use this polymod to fix the bug errors  
commands: haxelib remove polymod  
haxelib git polymod https://github.com/McJonnycat/old-polymod

**Comment by YoshiCrafter29** [comment]
New charter in progress, closing the issue
