### ISSUE TITLE
2 gf when custom skin

### ISSUE THREAD

**Issue by alarmingly** [YoshiCrafter29/YoshiEngine#13]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.2.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
play tutorial with custom gf skin
## Please describe your issue. Provide extensive detail and images if possible.2 gf and no gf animations
![custom skin make 2 gf(also no animations)](https://user-images.githubusercontent.com/83265784/150589281-f4be16a6-6232-4697-b162-c148392602a2.png)

**Comment by YoshiCrafter29** [comment]
Fixed in new version
