### ISSUE TITLE
Bug Report: [build bug]

### ISSUE THREAD

**Issue by Ezic123** [YoshiCrafter29/YoshiEngine#15]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.3.0
## Please describe your issue. Provide extensive detail and images if possible.
---
when I go to compile this error appears: Could not find haxelib "hxvm-lua", does it need to be installed?

**Comment by YoshiCrafter29** [comment]
haxelib install hxvm-lua https://www.github.com/YoshiCrafter29/hxvm-lua

**Comment by Ezic123** [comment]
ok 👍
