### ISSUE TITLE
Bug Report: [yoshi engine not open]

### ISSUE THREAD

**Issue by Ezic123** [YoshiCrafter29/YoshiEngine#20]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.3.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
no, i just downloaded and opened the engine
## Please describe your issue. Provide extensive detail and images if possible.
---I don't know if this problem is in the engine or it's in my pc, the yoshi engine doesn't open in my pc and the first versions opened and repeating I don't know if this problem is in the engine or it's in my pc

**Comment by YoshiCrafter29** [comment]
It's weird, cause other people are having this issue as well.
Can you tell me which version of Windows you're running on ? Along with the architecture ?
As far as i tried it both works on Windows 8 and 10.
Can you also give me what GPU (or APU) you're using, and the latest version that worked ?

**Comment by Ezic123** [comment]
i'm using windows 10 and i don't know what gpu or apu ;-;

**Comment by YoshiCrafter29** [comment]
Does your username have any ' or & or any other special characters in it ?

If so, try opening Yoshi Engine that way :
- Create a text file in the Yoshi Engine folder
- Type this in it :
`"Yoshi Engine.exe"`
- Close Notepad
- Enable "Show files extensions"
- Rename "your text file.txt" to "your text file.bat"
- Click yes on the dialog box
- Double click the bat file

**Comment by Ezic123** [comment]
It worked!
