### ISSUE TITLE
Enhancement: Linux builds

### ISSUE THREAD

**Issue by ThatOneCalculator** [YoshiCrafter29/YoshiEngine#24]
Adding Linux builds to the releases section would be very appreciated :)

**Comment by YoshiCrafter29** [comment]
I'll check if i can install an Ubuntu VM that can compiles the game, since compiling from Windows results in Neko (which is not hxcpp, and not compatible with the engine)

**Comment by ThatOneCalculator** [comment]
> i can build for linux because i use it as my base OS and i want to know if you fr want it

I run Linux too, but it's better to have this done with CI/CD (i.e. AppVeyor) so that the binaries can be trusted.

**Comment by YoshiCrafter29** [comment]
Fixed actions, that means Linux builds are now available.
