### ISSUE TITLE
Help: how do you add an FlxSprite with a lua script?

### ISSUE THREAD

**Issue by kittstone** [YoshiCrafter29/YoshiEngine#26]
## What do you need help for ?

refer to title

#### Please note that the documentation is still under construction.

**Comment by YoshiCrafter29** [comment]
Check the code sample [here](https://github.com/YoshiCrafter29/Yoshi-Engine-code-samples/blob/main/Add%20a%20FlxSprite.lua).

Also check the [Lua documentation](https://github.com/YoshiCrafter29/YoshiEngine/blob/main/documentation/doc/lua.md) for more info
