### ISSUE TITLE
Suggestion: Show  keybinds under arrows upon song start

### ISSUE THREAD

**Issue by jayden8923** [YoshiCrafter29/YoshiEngine#3]
## What is your suggestion, and why should it be implemented?
---
I am suggesting the ability to view the keybinds in the song when it starts in a way similar to shaggy, and maybe a function that allows you to prompt the keybind view

**Comment by YoshiCrafter29** [comment]
Implemented `PlayState.showKeys();` to do that exact effect.
Will be available in the next version of the engine
