### ISSUE TITLE
Bug Report: When changing downscroll in modchart the gray notes dont move to the top or the bottom

### ISSUE THREAD

**Issue by jayden8923** [YoshiCrafter29/YoshiEngine#4]
## Which target are you using?
- [X ] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.0.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
Add modchart to song
Change EngineSettings.downscroll to true/false in modchart mid song

## Please describe your issue. Provide extensive detail and images if possible.
When I use a modchart to change downscroll midsong in the beathit function the gray notes do not move up or down, but stay in the place they were in previously. The colored notes still move down or up and will move above or below the gray notes.
---
![image](https://user-images.githubusercontent.com/45021556/147372215-34fca771-367b-4c3d-8dd5-d7a5da64a580.png)

**Comment by YoshiCrafter29** [comment]
Oh actually the engine isnt designed to automatically move arrows from bottom to top when the downscroll value is changed. This allows people to program their smooth transition during switch. However, i should add a function to auto switch these.

**Comment by YoshiCrafter29** [comment]
`PlayState.setDownscroll(downscroll:Bool, autoPos:Bool)`

Will be available in the next Yoshi Engine version.
