### ISSUE TITLE
Bug Report: Game crashing when opening the debug menu

### ISSUE THREAD

**Issue by ImSamity** [YoshiCrafter29/YoshiEngine#45]
I'm using the Windows version of the engine

The version is 1.5.1

So when I tried changing characters of course I need to open the debug menu, but my game crashed and it said : Null Object Reference
![image](https://user-images.githubusercontent.com/93523300/153765351-3bd6806e-e16f-413c-ac68-893cc65ee9bf.png)

**Comment by YoshiCrafter29** [comment]
Managed to replicate the issue (it happens when the selected mod has no characters)

Fixing it rn

**Comment by YoshiCrafter29** [comment]
Fixed
