### ISSUE TITLE
Week 6 dialogue issue 

### ISSUE THREAD

**Issue by star-fran** [YoshiCrafter29/YoshiEngine#46]
## Which target are you using?
- [x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?

1.5.1

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

playing week 6 on history mode

## Please describe your issue. Provide extensive detail and images if possible.
when playing the week 6 on history mode, you cant skip any dialogue and that makes the week 6 unplayable

**Comment by YoshiCrafter29** [comment]
Should probably recode the Week 6 dialogue system, since this port was quickly made.

Will come out with a fix soon

**Comment by YoshiCrafter29** [comment]
Fixed
