### ISSUE TITLE
Null Object Reference when adding new sprite in Stage Editor

### ISSUE THREAD

**Issue by ThePootisBird** [YoshiCrafter29/YoshiEngine#48]
This is happening on Windows
V1.51
The stage is called "angelisland" as it is a Sonic.exe port just to get the hang of the engine
I created the stage, went to edit it, made a new sprite, called it "Sky" and then when i went to select the path it did this
![Screenshot_2549](https://user-images.githubusercontent.com/30559271/153772310-ce747d16-a5d1-4921-a40d-9ee3d81667bf.png)

**Comment by YoshiCrafter29** [comment]
Fixed in dev branch
