### ISSUE TITLE
Custom Stage doesn't load in song.

### ISSUE THREAD

**Issue by S4mueldaCosta** [YoshiCrafter29/YoshiEngine#51]
On Windows
V1.5.2
Even when I created the modchart the stage doesn't load
![8baff5bacd891951f63083b36a103596](https://user-images.githubusercontent.com/99627176/153938412-82870ea6-82e5-4a8d-8c5a-1e1ba8f9284f.png)

**Comment by YoshiCrafter29** [comment]
- Replace the [] by the {}
- Make sure it's added in the song_conf.json / .hx
- Check the logs
