### ISSUE TITLE
Bug Report: Chart Crashing

### ISSUE THREAD

**Issue by CharlesRBLX** [YoshiCrafter29/YoshiEngine#58]
![unknown (2)](https://user-images.githubusercontent.com/99976788/154702916-1be1ba15-2a60-44ac-bae5-6a3bfcdfe1d4.png)

Idk how this happened, but when i tried to grab a psych engine chart that had no events, and then that happened.

**Comment by YoshiCrafter29** [comment]
make sure there's a Inst.ogg (at least) in Your Mod/songs/your song/

**Comment by CharlesRBLX** [comment]
there was both an inst, and a voice file, but it does that anyways.

**Comment by YoshiCrafter29** [comment]
Fixed the FlxBar issue in the new update.
