### ISSUE TITLE
Bug Report: Action Builds DONT wORK

### ISSUE THREAD

**Issue by B01Coding** [YoshiCrafter29/YoshiEngine#61]
## Which target are you using?
- [x] Windows
- [ ] Linux
- [ ] Mac

## What version of the engine are you using (Bottom left of the screen in main menu) ?
Actionbuild
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
https://github.com/YoshiCrafter29/YoshiEngine/actions
## Please describe your issue. Provide extensive detail and images if possible.
---X on action build no work :(

**Comment by YoshiCrafter29** [comment]
Fixed the Linux one. Windows was already fixed.
