### ISSUE TITLE
'Character Changing'

### ISSUE THREAD

**Issue by MarcYdoesShit** [YoshiCrafter29/YoshiEngine#63]
## What do you need help for ?

How can i change the enemy's sprites and offsets mid-song?

**Comment by YoshiCrafter29** [comment]
[Check this example script here](https://github.com/YoshiCrafter29/Yoshi-Engine-code-samples/blob/main/Haxe/Change%20Character%20mid-song.hx) and [Check how to use the song_conf](https://github.com/YoshiCrafter29/YoshiEngine/wiki/Song-Configuration)
