### ISSUE TITLE
Bug Report: when I play thorns spirit doesnt load

### ISSUE THREAD

**Issue by derynyl** [YoshiCrafter29/YoshiEngine#65]
## Which target are you using?
- [ x] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ? 
v0.2.7.1

## Please describe your issue. Provide extensive detail and images if possible.
---
![image](https://user-images.githubusercontent.com/100978633/156860588-d535be7e-e53a-47ec-8bf7-e24a6f1ed5e6.png)
When I play thorns on freeplay or story mode spirit doesnt load

**Comment by YoshiCrafter29** [comment]
Fixed in 1.6.1
![image](https://user-images.githubusercontent.com/81191621/156863398-801c354a-9b94-4735-854e-31914449cdf2.png)
