### ISSUE TITLE
Bug Report: Note tails are offset to the left with middlescroll on

### ISSUE THREAD

**Issue by Cornbread18** [YoshiCrafter29/YoshiEngine#66]
## Which target are you using?
- [ X ] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?

V1.6.0

## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.

Simply enabling middlescroll creates the issue.

## Please describe your issue. Provide extensive detail and images if possible.

When middlescroll is enabled, all note tails/holds are offset to the left, instead of directly above the note. 
This is one of my first issues on github, so sorry if it's a little lackluster.

![image](https://user-images.githubusercontent.com/34987803/156860538-6f1940db-a366-42ee-a40d-26dff4f71e58.png)
![image](https://user-images.githubusercontent.com/34987803/156860622-b3d238d5-3fde-4ded-b357-6a043416c6fd.png)

**Comment by YoshiCrafter29** [comment]
Fixed in dev branch
