### ISSUE TITLE
UI is misaligned and cropped wrong on taller monitors

### ISSUE THREAD

**Issue by alarmingly** [YoshiCrafter29/YoshiEngine#7]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.1.0
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
use taller monitor 16:10
## Please describe your issue. Provide extensive detail and images if possible.
the UI is misaligned and just not correctly cropped on my 16:10 monitor
![misaligned](https://user-images.githubusercontent.com/83265784/148277917-3e704a1e-3d6c-443b-9542-4eef398f3828.png)
![yoshi engine hmm](https://user-images.githubusercontent.com/83265784/148277918-677c6c61-d0ed-4b4a-bdb8-14729b889b7e.png)

**Comment by YoshiCrafter29** [comment]
fixed
![image](https://user-images.githubusercontent.com/81191621/148293094-4fdf10fa-8f68-4bf3-aaba-8fd450d1539b.png)

**Comment by YoshiCrafter29** [comment]
(Will be available in v1.1.1 or v1.2.0 idk)
