### ISSUE TITLE
Bug Report: Scrolling and camera speed are tied to the framerate

### ISSUE THREAD

**Issue by sayofthelor** [YoshiCrafter29/YoshiEngine#73]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## Please describe your issue. Provide extensive detail and images if possible.
---
When you scroll, or when the camera moves, it is very noticably faster when you do it at a higher framerate. I'll try and make a pull request for this if I can figure out how to fix it.

**Comment by YoshiCrafter29** [comment]
I ironically fixed it without even knowing this issue existed lmao
