### ISSUE TITLE
Enhancement: I LOVE YOU SOOO MUCH 

### ISSUE THREAD

**Issue by McJonnycat** [YoshiCrafter29/YoshiEngine#74]
YOU HELPED ME FIX ALOT OF MODS THAT I HAVE DIFFICULTY FIXING SHADERS!!!! I LOVE YOU YOSHI!!!!!

**Comment by Mr-funkinguy** [comment]
Yoshi = mid

**Comment by YoshiCrafter29** [comment]
Nice!
