### ISSUE TITLE
Bug Report: [i was wondering if i can use this FlxFixedShader]

### ISSUE THREAD

**Issue by McJonnycat** [YoshiCrafter29/YoshiEngine#75]
im on a mac and i was wondering if i can use this shader code

**Comment by YoshiCrafter29** [comment]
You can use `CustomShader` which is basically FlxFixedShader, but soft coded

In your mods folder, create a "shader" folder, then add a shader .frag file (for the fragment shader).

Then in a modchart, do this:
```haxe
function createPost() {
     var shader = new CustomShader(mod + ':shaderFileNameWithoutExtension');
     PlayState.boyfriend.shader = shader;
}```

This will apply your shader to Boyfriend.

**Comment by McJonnycat** [comment]
can this work on diffrent engines as well

**Comment by YoshiCrafter29** [comment]
Soft coded like Psych: no, since there isn't soft coded shaders support
Source Code: Yes

**Comment by McJonnycat** [comment]
i mean't like kade engine

**Comment by McJonnycat** [comment]
or any other one

**Comment by McJonnycat** [comment]
most of your code is there and i am sorry for stealing your code

**Comment by McJonnycat** [comment]
so thats why i had to ask permission
