### ISSUE TITLE
Enemy and Player animations freeze after hitting note

### ISSUE THREAD

**Issue by alarmingly** [YoshiCrafter29/YoshiEngine#8]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.1.0
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
play game
## Please describe your issue. Provide extensive detail and images if possible.
---
![more freeze](https://user-images.githubusercontent.com/83265784/148392753-717e4e18-2496-4b25-9f94-428ff3715885.png)
![freeze](https://user-images.githubusercontent.com/83265784/148392758-a5015f4c-5d8d-40a5-921f-d410e63d8e86.png)

**Comment by alarmingly** [comment]
![nooooooooo](https://user-images.githubusercontent.com/83265784/148393374-9415d402-2807-4ab5-898b-24498007d45e.png)
even more

**Comment by YoshiCrafter29** [comment]
Character debug mode is enabled, disable it in the settings menu.
