### ISSUE TITLE
Custom Icons do not work

### ISSUE THREAD

**Issue by alarmingly** [YoshiCrafter29/YoshiEngine#9]
## Which target are you using?
- [X] Windows
- [ ] Mac
- [ ] Linux

## What version of the engine are you using (Bottom left of the screen in the main menu)?
1.1.0
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
try to add custom icon
## Please describe your issue. Provide extensive detail and images if possible.
---
![where icon](https://user-images.githubusercontent.com/83265784/148649118-3aee9aef-96c6-4284-a23f-2f05c518dd05.png)
I made a skin for the game using assets from the VS. RetroSpecter mod and the icons do not show up

**Comment by YoshiCrafter29** [comment]
That bug !
Yeah i'm aware of it, it only works on charts that have "bf" as Player1

I'm remaking the skin system so it's going to be fixed and more advanced.

**Comment by YoshiCrafter29** [comment]
Fixed
