### ISSUE TITLE
Bug Report: how do i fix the lag in certain shaders? 

### ISSUE THREAD

**Issue by McJonnycat** [YoshiCrafter29/YoshiEngine#91]
i was wondering if there is a code where the laggyness of the shaders don't lag. and no this not your shaders that are laggy its someone else shaders that are laggy when i play there game.

**Comment by YoshiCrafter29** [comment]
Sound like a haxeflixel issue, are you sure your shader is optimized and don't lag the game on source code?

If it works on source code, maybe you're putting your code in the wrong like, ex: `beatHit` or `curBeat` instead of in `update`

**Comment by YoshiCrafter29** [comment]
Closed due to inactivity
