### ISSUE TITLE
is there a way to change the character and stage mid song

### ISSUE THREAD

**Issue by kermityourfriend1** [YoshiCrafter29/YoshiEngine#92]
i dont know how to do it

**Comment by YoshiCrafter29** [comment]
[Check this example for the characters](https://github.com/YoshiCrafter29/Yoshi-Engine-code-samples/blob/main/Haxe/Change%20Character%20mid-song.hx)

And for the stage:

```haxe
stage.destroy();
stage = loadStage("second-stage");
```
