### ISSUE TITLE
Bug Report: Week file don't load

### ISSUE THREAD

**Issue by Jsa010** [YoshiCrafter29/YoshiEngine#93]
#### Please check for duplicates or similar issues, as well performing simple troubleshooting steps (such as deleting the YoshiCrafter29 folder from AppData) before submitting an issue.
not source :v
#### If you're using an older version of the engine, check if the bug haven't been already fixed
newest
##### PS : the "everything goes black while changing state in developer mode bug" is not a bug, it's been designed this way to refresh all bitmaps between states to allow easier modding.
i didn't know that
## Which target are you using?
- [ ] Windows
## What version of the engine are you using (Bottom left of the screen in main menu) ?
1.6.1
## Have you identified any steps to reproduce the bug? If so, please describe them below in as much detail as possible. Use images if possible.
no
## Please describe your issue. Provide extensive detail and images if possible.
---
i was making a week and the week file never loaded and stay with haxe logo,plz help

**Comment by YoshiCrafter29** [comment]
Fixed in dev branch
